# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mF4jL6ifzfUu88rmUjTurOXc037FJwwy
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

data=pd.DataFrame({
    "x":np.random.randn(100),
    "y":np.random.randn(100),
    "value":np.random.randn(100)
})
cmap="viridis"
alpha=1
plt.figure(figsize=(6,6))
plt.scatter(data["x"],data["y"],c=data["value"],cmap=cmap,alpha=alpha)
plt.xlabel("X-axis")
plt.ylabel("Y-axis")
plt.title("scatterplot with colormap")
plt.colorbar(label="value")
plt.show()

